### ISSUE TITLE
npm start is broken. npm run build pulls up webpack.js. Does not create /public

### ISSUE THREAD

**Issue by hopkinsjj9** [jussikinnula/angular-socket-io-chat#1]
C:\Users\Jack\Documents\angLinked\angular2-socketio-chat-example-master>npm start

> angular2-socketio-chat-example@0.0.2 start C:\Users\Jack\Documents\angLinked\angular2-socketio-chat-example-
> master
> node public/server.js

module.js:327
    throw err;
    ^

Error: Cannot find module 'C:\Users\Jack\Documents\angLinked\angular2-socketio-chat-example-master\public\serv
er.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\Jack\AppData\Roaming\npm\node_modules\npm
\bin\npm-cli.js" "start"
npm ERR! node v4.4.5
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! angular2-socketio-chat-example@0.0.2 start: `node public/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-socketio-chat-example@0.0.2 start script 'node public/server.js'.
npm ERR! This is most likely a problem with the angular2-socketio-chat-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node public/server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular2-socketio-chat-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Jack\Documents\angLinked\angular2-socketio-chat-example-master\npm-debug.log

C:\Users\Jack\Documents\angLinked\angular2-socketio-chat-example-master>npm run build

> angular2-socketio-chat-example@0.0.2 build C:\Users\Jack\Documents\angLinked\angular2-socketio-chat-example-
> master
> webpack --config webpack.js

C:\Users\Jack\Documents\angLinked\angular2-socketio-chat-example-master>

**Comment by hopkinsjj9** [comment]
I was able to fix the above issue.

#1 npm i webpack -g
#2 renamed webpack.js to webpack.config.js
#3 npm i autoprefixer
#4 webpack --config webpack.config.js
#5 npm start
